# -*- coding: utf-8 -*-
"""Reading AEMO Data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rHFl8BKennyy95L-ho1ArHTf9pr41aUh
"""

import pandas as pd
import numpy as np
import datetime

today = datetime.datetime.now()
aemo_data = []
year = str(today.year)
for i in range(1,13):
  month = str(i)
  if i in range(1, 10):
    month = str(i).zfill(2)
  url="https://www.aemo.com.au/aemo/data/nem/priceanddemand/PRICE_AND_DEMAND_"+year+month+"_NSW1.csv"
  try:
      aemo_month=pd.read_csv(url,index_col='SETTLEMENTDATE', parse_dates=True) 
      aemo_data.append(aemo_month)
  except:
    print("Year not found")

df = pd.concat(aemo_data)
print(df.head())
print(df.tail())